### ISSUE TITLE
Project not working. Need help!

### ISSUE THREAD

**Issue by decoded-cipher** [d17012002/InVITe#1]
Hey @sakshgupta @devanshuyadav @d17012002 

Recently I came across this interesting project of yours. But when I tried to run it locally, I started facing some errors.

- **Server** module ran successfully.
- **Developer** module throws the following issue:

![image](https://user-images.githubusercontent.com/44474792/229602128-00719759-c7cc-4f7d-8262-0aee7affb178.png)

- **Client** Module also throws an error as follows:

![image](https://user-images.githubusercontent.com/44474792/229602861-25268f11-5121-40ff-b70d-e16b460c897b.png)

Hereby attaching the debug-log file : [2023-04-03T19_03_51_263Z-debug.log](https://github.com/d17012002/InVITe/files/11141613/2023-04-03T19_03_51_263Z-debug.log)

Thanks in advance.
Expecting a faster reply!

**Comment by sakshgupta** [comment]
Hey @decoded-cipher,

Thank you for bringing this issue to our attention. We appreciate your feedback.

We are currently looking into this and trying to recreate the issue on our end. Please give us some time to investigate further. We will keep you updated on the progress.

Thank you for your patience.

Best regards,
Saksham Gupta

**Comment by sakshgupta** [comment]
I have tried to recreate the issue but was unsuccessful in doing so. To further investigate and resolve this problem, I kindly request that you provide me with more details regarding the exact steps you followed to encounter this issue. This will help me to better understand the problem and work towards a solution.

**Comment by decoded-cipher** [comment]
Thank you @sakshgupta for your faster response.
To my knowledge, I just followed the steps mentioned in the [Getting Started](https://github.com/d17012002/InVITe#-getting-started).

**Comment by sakshgupta** [comment]
I suggest that you try cloning the repository again and follow the updated instructions in the README file to run the website locally. I have added more details on how to install dependencies and set up environment variables, which might help resolve the problem. Please let me know if you still encounter the issue after trying these steps. 
Thank you!

**Comment by decoded-cipher** [comment]
Thank you so much for the faster response....
The project works now! The problem was, the version of Node that I was using, was quite an old one - `v12.x.x`. I forgot to switch back to the stable latest version. Now it works just fine.

---

While running the project, I came across something blocking me from SignUp - `Enter VIT Registration Number`. It throws an error like, the Registration Number is not valid. Kindly help me resolve the issue. If possible, can you share me a sample working format of a VIT Registration Number or else.

**Comment by decoded-cipher** [comment]
Hey @sakshgupta @devanshuyadav @d17012002 ,

- How can an Admin create new events?
- The + icon on the Admin Dashboard leads to a 404 page.

![image](https://user-images.githubusercontent.com/44474792/229747758-8de873f5-6204-4a80-b3e4-4030d0416c5c.png)

Thanks in advance.

**Comment by sakshgupta** [comment]
> Thank you so much for the faster response.... The project works now! The problem was, the version of Node that I was using, was quite an old one - `v12.x.x`. I forgot to switch back to the stable latest version. Now it works just fine.
> 
> While running the project, I came across something blocking me from SignUp - `Enter VIT Registration Number`. It throws an error like, the Registration Number is not valid. Kindly help me resolve the issue. If possible, can you share me a sample working format of a VIT Registration Number or else.

No problem at all, we're glad that the issue got resolved for you. As for the registration number error, the format for VIT registration number is generally XXYYYNNNNN. As an example, a VIT registration number could be 20BCE11111.

**Comment by sakshgupta** [comment]
> Hey @sakshgupta @devanshuyadav @d17012002 ,
> 
> * How can an Admin create new events?
> * The + icon on the Admin Dashboard leads to a 404 page.
> 
> ![image](https://user-images.githubusercontent.com/44474792/229747758-8de873f5-6204-4a80-b3e4-4030d0416c5c.png)
> 
> Thanks in advance.



> Hey @sakshgupta @devanshuyadav @d17012002 ,
> 
> * How can an Admin create new events?
> * The + icon on the Admin Dashboard leads to a 404 page.

what's happening here is that if you write 'eventForm' in the URL instead of 'eventform' it's working. I tried pushing the correct name in the GitHub but it won't address the changes. 
I committed a possible fix.
For now you can try changing the filename in client/src/pages/admin/eventForm.jsx to eventform.jsx

**Comment by sakshgupta** [comment]
Fixed the issue with eventform not working
